services:
  openpi_server:
    build:
      network: host
      args:
        HTTP_PROXY: http://127.0.0.1:7897
        HTTPS_PROXY: http://127.0.0.1:7897
        http_proxy: http://127.0.0.1:7897
        https_proxy: http://127.0.0.1:7897
        NO_PROXY: localhost,127.0.0.1,::1
        no_proxy: localhost,127.0.0.1,::1
    environment:
      HTTP_PROXY: http://127.0.0.1:7897
      HTTPS_PROXY: http://127.0.0.1:7897
      http_proxy: http://127.0.0.1:7897
      https_proxy: http://127.0.0.1:7897
      NO_PROXY: localhost,127.0.0.1,::1
      no_proxy: localhost,127.0.0.1,::1
      GCSFS_TOKEN: anon